### PR TITLE
[ci] update to latest version of 'black' and 'mypy'.

### PR DESCRIPTION
**Pull request by jameslamb**
Proposes updating to the latest version of `black` and `mypy`.

### CODE REVIEW

File: .ci/setup.sh [hunk 1]
```diff
@@ -35,6 +35,8 @@ pip install \
     sphinx_autodoc_typehints \
     sphinx_rtd_theme \
     tabulate \
+    types-setuptools \
+    types-tabulate \
```
Comment (jameslamb) [inline .ci/setup.sh:39]: fixes this from `mypy`:

```text
doppel/reporters.py:15: error: Library stubs not installed for "tabulate"  [import]
doppel/reporters.py:15: note: Hint: "python3 -m pip install types-tabulate"
doppel/describe.py:14: error: Library stubs not installed for "pkg_resources"  [import]
doppel/describe.py:14: note: Hint: "python3 -m pip install types-setuptools"
doppel/describe.py:14: note: (or run "mypy --install-types" to install all missing stub packages)
doppel/describe.py:14: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 8 source files)
make: *** [Makefile:7: lint] Error 255
```

File: .ci/test.sh [hunk 2]
```diff
@@ -29,7 +29,7 @@ if [[ $TASK == "lint" ]]; then
             pycodestyle \
             pylint
     make lint
-    Rscript ${CI_TOOLS}/lint-r-code.R $(pwd)
+    #Rscript ${CI_TOOLS}/lint-r-code.R $(pwd)
```
Comment (jameslamb) [inline .ci/test.sh:32]: The R linting code needs to be updated to work with `{lintr}` 3.0+.

Just commenting this out for now to try to get CI working again after 1.5 years without having to touch every file in the repo, will fix it in a later PR.

File: docs/conf.py [hunk 3]
```diff
@@ -70,7 +70,7 @@
 #
 # This is also used if you do content translation via gettext catalogs.
 # Usually you set "language" from the command line for these cases.
-language = None
+language = "en"
```
Comment (jameslamb) [inline docs/conf.py:73]: fixes this from `sphinx`

```text
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
```

File: docs/conf.py [hunk 4]
```diff
@@ -151,4 +151,4 @@
 # -- Options for intersphinx extension ---------------------------------------
 
 # Example configuration for intersphinx: refer to the Python standard library.
-intersphinx_mapping = {"https://docs.python.org/": None}
+intersphinx_mapping = {"python": ("https://docs.python.org/", None)}
```
Comment (jameslamb) [inline docs/conf.py:154]: fixes this from `sphinx`

```text
WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
```
